Create solution, implement announce endpoints
LBPUnion/Lighthouse2 pull request #21
Opened 2024-07-04 17:57 UTC by Metraberryy

getting this thing started

2024-07-04 18:06 UTC, sudokoko requested changes

2024-07-04 18:06 UTC, sudokoko commented on Lighthouse2/Lighthouse2/Lighthouse2.csproj
> +
Add default namespace and assembly name
```suggestion
    <PropertyGroup>
        <RootNamespace>LBPUnion.Lighthouse2</RootNamespace>
        <AssemblyName>LBPUnion.Lighthouse2</AssemblyName>
    </PropertyGroup>

```

2024-07-04 18:06 UTC, sudokoko commented on Lighthouse2/Lighthouse2.sln.DotSettings
Preferrably styling rules should be introduced later and then we can just run the formatter

2024-07-04 22:16 UTC, Slendy requested changes
I think this is a solid start, just some minor nitpicks from me

2024-07-04 22:16 UTC, Slendy commented on Lighthouse2/Controllers/LoginController.cs
> +public class LoginController : ControllerBase
Only a suggestion, but should we have a separate GameController class like [the one I implemented in a PR](https://github.com/LBPUnion/ProjectLighthouse/blob/0e0a900f67136f2c9f0575ddc9d6ec5f729d3d78/ProjectLighthouse.Servers.GameServer/Types/GameController.cs) to reduce the duplication of the attributes, especially as we add more in the future.

2024-07-04 22:16 UTC, Slendy commented on Lighthouse2/Lighthouse2.csproj
> +        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0"/>
```suggestion
```
These dependencies aren't required yet

2024-07-05 02:04 UTC, sudokoko approved these changes

2024-07-05 03:27 UTC, Slendy approved these changes

2024-11-04 01:44 UTC, sudokoko commented
@Metraberryy is this still good to merge? Just wanted to see if there were any changes you wanted to propose since writing this PR.

2024-11-04 02:27 UTC, Metraberryy commented
yeah, seems good to me

2024-11-04 02:28 UTC, merged